version: '3.8'

services:
  # Define the PostgreSQL service
  db:
    image: postgres:13
    container_name: pg-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Define the Go application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg-app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=test
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
